<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 .\WALLET.glb --T --draco /draco/
-->

<script>
  import { T } from '@threlte/core'
  import { useGltf, useDraco } from '@threlte/extras'

  let { fallback, error, children, ref = $bindable(), ...props } = $props()

  const gltf = useGltf('/WALLET-transformed.glb', { dracoLoader: useDraco() })
</script>

<T.Group
  bind:ref
  dispose={false}
  {...props}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Group position={[0, 4, 0]}>
      <T.Mesh
        geometry={gltf.nodes.Cube006.geometry}
        material={gltf.nodes.Cube006.material}
        position={[-1.4, -3.73, 0.45]}
        scale={[0.25, 0.5, 0.05]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube007.geometry}
        material={gltf.nodes.Cube007.material}
        position={[-0.7, -3.58, 0.45]}
        scale={[0.25, 0.5, 0.05]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube008.geometry}
        material={gltf.nodes.Cube008.material}
        position={[0, -3.43, 0.45]}
        scale={[0.25, 0.5, 0.05]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube009.geometry}
        material={gltf.nodes.Cube009.material}
        position={[0.7, -3.28, 0.45]}
        scale={[0.25, 0.5, 0.05]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube010.geometry}
        material={gltf.nodes.Cube010.material}
        position={[1.4, -3.13, 0.45]}
        scale={[0.25, 0.5, 0.05]}
      />
      <T.Mesh
        geometry={gltf.nodes.Grafica_1.geometry}
        material={gltf.materials['Material.008']}
        position={[0, -3.1, 0.3]}
        scale={[1.8, 1, 0.05]}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane001.geometry}
        material={gltf.nodes.Plane001.material}
        position={[-1.1, -2.45, 0.45]}
        rotation={[Math.PI / 2, Math.PI / 2, 0]}
      />
    </T.Group>
    <T.Group position={[0, 4, 0]}>
      <T.Mesh
        geometry={gltf.nodes.Cube017.geometry}
        material={gltf.nodes.Cube017.material}
        position={[0, -5.2, 0.3]}
        scale={[1.8, 1, 0.05]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube.geometry}
        material={gltf.nodes.Cube.material}
        position={[-1.4, -4.7, 0.45]}
        scale={[0.25, 0.25, 0.05]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube019.geometry}
        material={gltf.nodes.Cube019.material}
        position={[0.9, -5.2, 0.45]}
        scale={[0.75, 0.75, 0.05]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube020.geometry}
        material={gltf.nodes.Cube020.material}
        position={[-0.8, -4.7, 0.45]}
        scale={[0.25, 0.25, 0.05]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube021.geometry}
        material={gltf.nodes.Cube021.material}
        position={[-0.8, -5.7, 0.45]}
        scale={[0.25, 0.25, 0.05]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube022.geometry}
        material={gltf.nodes.Cube022.material}
        position={[-1.4, -5.7, 0.45]}
        scale={[0.25, 0.25, 0.05]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube023.geometry}
        material={gltf.nodes.Cube023.material}
        position={[-0.2, -4.7, 0.45]}
        scale={[0.25, 0.25, 0.05]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube024.geometry}
        material={gltf.nodes.Cube024.material}
        position={[-0.2, -5.7, 0.45]}
        scale={[0.25, 0.25, 0.05]}
      />
    </T.Group>
    <T.Group position={[0, 4, 0]}>
      <T.Mesh
        geometry={gltf.nodes.Cylinder.geometry}
        material={gltf.materials['Material.002']}
        position={[-1.6, -1.59, 0.36]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.1}
      />
      <T.Mesh
        geometry={gltf.nodes.Cylinder001.geometry}
        material={gltf.materials['Material.003']}
        position={[-1.3, -1.59, 0.36]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.1}
      />
      <T.Mesh
        geometry={gltf.nodes.Cylinder002.geometry}
        material={gltf.materials['Material.004']}
        position={[-1, -1.59, 0.36]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.1}
      />
    </T.Group>
    <T.Mesh
      geometry={gltf.nodes.header.geometry}
      material={gltf.materials['Material.009']}
      position={[0, 2.4, 0.3]}
      scale={[1.8, 0.4, 0.05]}
    />
    <T.Mesh
      geometry={gltf.nodes.phone.geometry}
      material={gltf.nodes.phone.material}
      scale={[2, 3, 0.15]}
    />
    <T.Mesh
      geometry={gltf.nodes.menu001.geometry}
      material={gltf.materials['Material.009']}
      position={[0, -2.55, 0.3]}
      scale={[1.8, 0.25, 0.05]}
    >
      <T.Group
        position={[-0.71, -0.4, 3]}
        scale={[0.22, 0.2, 1]}
      >
        <T.Mesh
          geometry={gltf.nodes.Cube060.geometry}
          material={gltf.materials['Material.014']}
        />
        <T.Mesh
          geometry={gltf.nodes.Cube060_1.geometry}
          material={gltf.materials['Material.015']}
        />
      </T.Group>
      <T.Group
        position={[0.01, 0.43, 3]}
        rotation={[0, 0, Math.PI]}
        scale={[0.33, 0.2, 1]}
      >
        <T.Mesh
          geometry={gltf.nodes.Cube061.geometry}
          material={gltf.materials['Material.021']}
        />
        <T.Mesh
          geometry={gltf.nodes.Cube061_1.geometry}
          material={gltf.materials['Material.015']}
        />
      </T.Group>
      <T.Mesh
        geometry={gltf.nodes.Cube039.geometry}
        material={gltf.materials['Material.028']}
        position={[0.7, -0.4, 3]}
        scale={[0.22, 0.2, 1]}
      />
    </T.Mesh>
    <T.Mesh
      geometry={gltf.nodes.aptos.geometry}
      material={gltf.nodes.aptos.material}
      position={[1.63, 2.65, 0.45]}
      rotation={[Math.PI / 2, 0, 0]}
      scale={[1.09, 1.09, 1.27]}
    />
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
