[package]
name = "pay"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = "2.8.2"
openzeppelin_token = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.20.0" }

[dev-dependencies]
snforge_std_deprecated = "0.48.1"
assert_macros = "2.8.2"

[[target.starknet-contract]]
sierra = true
casm = true

[scripts]
test = "snforge test"

[tool.scarb]
allow-prebuilt-plugins = ["snforge_std_deprecated"]
