<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 .\WALLET.glb --T --draco /draco/
-->

<script lang="ts">
	import { T, useTask } from '@threlte/core';
	import {
		FakeGlowMaterial,
		HTML,
		interactivity,
		MeshLineMaterial,
		Outlines,
		RadialGradientTexture,
		useDraco,
		useGltf
	} from '@threlte/extras';
	import { Spring } from 'svelte/motion';
	import { DoubleSide } from 'three';

	let { fallback = () => {}, error = () => {}, children = () => {}, ...props } = $props();

	const gltf = useGltf('/WALLET-transformed.glb', { dracoLoader: useDraco() });

	interactivity();
	const scale = new Spring(1);
	const scaleCube006 = new Spring(1);
	const scaleCube007 = new Spring(1);
	const scaleCube008 = new Spring(1);
	const scaleCube009 = new Spring(1);
	const scaleCube010 = new Spring(1);
	const scaleGrafica1 = new Spring(1);
	const scaleMenu001 = new Spring(1);
	const scaleCube060 = new Spring(1);
	const scaleCube060_1 = new Spring(1);
	const scaleCube061 = new Spring(1);
	const scaleCube061_1 = new Spring(1);
	const scaleCube039 = new Spring(1);

	let objectRef: any = $state<any>();
	let initialPositon: any = $state();

	$effect(() => {
		if (!objectRef) return;
		//@ts-ignore
		initialPositon = objectRef.position.y;
	});

	let elapse = 0;

	useTask((delta) => {
		if (!objectRef) return;
		elapse += delta;
		objectRef.position.y = initialPositon + Math.sin(elapse * 1) * 0.1;
	});
</script>

{#await gltf then gltf}
	<T.Group
		bind:ref={objectRef}
		name="container"
		position={[4.5, 0, -5]}
		rotation={[-0.3862, -0.8011, -0.256]}
		dispose={false}
		{...props}
	>
		<T.Group name="grafica_1" position={[0, 4, 0]}>
			<T.Mesh
				geometry={gltf.nodes.Cube006.geometry}
				material={gltf.nodes.Cube006.material}
				position={[-1.4, -3.73, 0.45]}
				scale={[0.25 * scaleCube006.current, 0.5 * scaleCube006.current, 0.05]}
				onpointerenter={() => {
					scaleCube006.target = 1.1;
				}}
				onpointerleave={() => {
					scaleCube006.target = 1;
				}}
			>
				<MeshLineMaterial lineWidth={0.02} color="#00bfff" />
			</T.Mesh>

			<T.Mesh
				geometry={gltf.nodes.Cube007.geometry}
				material={gltf.nodes.Cube007.material}
				position={[-0.7, -3.58, 0.45]}
				scale={[0.25 * scaleCube007.current, 0.5 * scaleCube007.current, 0.05]}
				onpointerenter={() => {
					scaleCube007.target = 1.1;
				}}
				onpointerleave={() => {
					scaleCube007.target = 1;
				}}
			>
				<MeshLineMaterial lineWidth={0.02} color="#8a2be2" />
			</T.Mesh>

			<T.Mesh
				geometry={gltf.nodes.Cube008.geometry}
				material={gltf.nodes.Cube008.material}
				position={[0, -3.43, 0.45]}
				scale={[0.25 * scaleCube008.current, 0.5 * scaleCube008.current, 0.05]}
				onpointerenter={() => {
					scaleCube008.target = 1.1;
				}}
				onpointerleave={() => {
					scaleCube008.target = 1;
				}}
			>
				<MeshLineMaterial lineWidth={0.02} color="#ff1497" />
			</T.Mesh>
			<T.Mesh
				geometry={gltf.nodes.Cube009.geometry}
				material={gltf.nodes.Cube009.material}
				position={[0.7, -3.28, 0.45]}
				scale={[0.25 * scaleCube009.current, 0.5 * scaleCube009.current, 0.05]}
				onpointerenter={() => {
					scaleCube009.target = 1.1;
				}}
				onpointerleave={() => {
					scaleCube009.target = 1;
				}}
			>
				<MeshLineMaterial lineWidth={0.02} color="#ffd700" />
			</T.Mesh>
			<T.Mesh
				geometry={gltf.nodes.Cube010.geometry}
				material={gltf.nodes.Cube010.material}
				position={[1.4, -3.13, 0.45]}
				scale={[0.25 * scaleCube010.current, 0.5 * scaleCube010.current, 0.05]}
				onpointerenter={() => {
					scaleCube010.target = 1.1;
				}}
				onpointerleave={() => {
					scaleCube010.target = 1;
				}}
			>
				<MeshLineMaterial lineWidth={0.02} color="#00bfff" />
			</T.Mesh>

			<T.Mesh
				geometry={gltf.nodes.Grafica_1.geometry}
				position={[0, -3.1, 0.3]}
				scale={[1.8 * scaleGrafica1.current, 1 * scaleGrafica1.current, 0.05]}
			>
				<!-- <MeshLineMaterial lineWidth={0.02} color="white" /> -->

				<T.MeshBasicMaterial>
					<RadialGradientTexture
						width={128}
						height={500}
						innerRadius={1}
						outerRadius="auto"
						center.x={1}
						center.y={0.5}
						stops={[
							{ color: '#fa6705', offset: 0 },
							{ color: '#fa0573', offset: 1 }
						]}
					/>
				</T.MeshBasicMaterial>
			</T.Mesh>

			<T.Mesh
				geometry={gltf.nodes.Plane001.geometry}
				material={gltf.nodes.Plane001.material}
				position={[-1.1, -2.45, 0.45]}
				rotation={[Math.PI / 2, Math.PI / 2, 0]}
				scale={scale.current}
				onpointerenter={() => {
					scale.target = 1.1;
				}}
				onpointerleave={() => {
					scale.target = 1;
				}}
			>
				<MeshLineMaterial lineWidth={0.02} color="#00bfff" />
				<T.Group
					name="grafica_1_balance"
					position={[-0.1, 0.2, 0.1]}
					rotation={[1.5708, 1.5708, 0]}
					scale={[1, 0.8, 0.7]}
				>
					<HTML
						name="balance"
						transform
						position={[0, 0, 0.1]}
						scale={0.5}
						rotation={[Math.PI / 2, Math.PI / 2, 0]}
						style="pointer-events: none; "
					>
						<div
							class="text-center bg-gradient-to-br from-cyan-500/20 to-purple-500/20 backdrop-blur-md border border-cyan-400/30 rounded-lg p-3 min-w-[120px] shadow-lg shadow-cyan-400/20"
						>
							<div class="text-xl font-bold white mb-1 font-mono drop-shadow-lg text-white">
								$12.47
							</div>
						</div>
					</HTML>
				</T.Group>
			</T.Mesh>
		</T.Group>

		<T.Group position={[0, 4, 0]}>
			<T.Mesh
				geometry={gltf.nodes.Cube017.geometry}
				material={gltf.nodes.Cube017.material}
				position={[0, -5.2, 0.3]}
				scale={[1.8, 1, 0.05]}
			>
				<T.MeshBasicMaterial side={DoubleSide}>
					<RadialGradientTexture
						width={512}
						height={512}
						innerRadius={0.1}
						outerRadius="auto"
						center.x={0.5}
						center.y={0.5}
						stops={[
							{ color: '#00bfff', offset: 0 },
							{ color: '#8a2be2', offset: 0.5 },
							{ color: '#ff1497', offset: 1 }
						]}
					/>
				</T.MeshBasicMaterial>
			</T.Mesh>
			<T.Mesh
				geometry={gltf.nodes.Cube.geometry}
				material={gltf.nodes.Cube.material}
				position={[-1.4, -4.7, 0.45]}
				scale={[0.25, 0.25, 0.05]}
			>
				<T.MeshBasicMaterial side={DoubleSide}>
					<RadialGradientTexture
						width={128}
						height={128}
						innerRadius={0.2}
						outerRadius="auto"
						center.x={0.5}
						center.y={0.5}
						stops={[
							{ color: '#00bfff', offset: 0 },
							{ color: '#ffd700', offset: 1 }
						]}
					/>
				</T.MeshBasicMaterial>
			</T.Mesh>

			<T.Mesh
				geometry={gltf.nodes.Cube019.geometry}
				material={gltf.nodes.Cube019.material}
				position={[0.9, -5.2, 0.45]}
				scale={[0.75, 0.75, 0.05]}
			>
				<T.MeshBasicMaterial side={DoubleSide}>
					<RadialGradientTexture
						width={512}
						height={512}
						innerRadius={0.2}
						outerRadius="auto"
						center.x={0.5}
						center.y={0.5}
						stops={[
							{ color: '#8a2be2', offset: 0 },
							{ color: '#00bfff', offset: 0.5 },
							{ color: '#ff1497', offset: 1 }
						]}
					/>
				</T.MeshBasicMaterial>
			</T.Mesh>
			<T.Mesh
				geometry={gltf.nodes.Cube020.geometry}
				material={gltf.nodes.Cube020.material}
				position={[-0.8, -4.7, 0.45]}
				scale={[0.25, 0.25, 0.05]}
			>
				<T.MeshBasicMaterial side={DoubleSide}>
					<RadialGradientTexture
						width={128}
						height={128}
						innerRadius={0.2}
						outerRadius="auto"
						center.x={0.5}
						center.y={0.5}
						stops={[
							{ color: '#ff1497', offset: 0 },
							{ color: '#8a2be2', offset: 1 }
						]}
					/>
				</T.MeshBasicMaterial>
			</T.Mesh>
			<T.Mesh
				geometry={gltf.nodes.Cube021.geometry}
				material={gltf.nodes.Cube021.material}
				position={[-0.8, -5.7, 0.45]}
				scale={[0.25, 0.25, 0.05]}
			>
				<T.MeshBasicMaterial side={DoubleSide}>
					<RadialGradientTexture
						width={128}
						height={128}
						innerRadius={0.2}
						outerRadius="auto"
						center.x={0.5}
						center.y={0.5}
						stops={[
							{ color: '#ffd700', offset: 0 },
							{ color: '#00bfff', offset: 1 }
						]}
					/>
				</T.MeshBasicMaterial>
			</T.Mesh>
			<T.Mesh
				geometry={gltf.nodes.Cube022.geometry}
				material={gltf.nodes.Cube022.material}
				position={[-1.4, -5.7, 0.45]}
				scale={[0.25, 0.25, 0.05]}
			>
				<T.MeshBasicMaterial side={DoubleSide}>
					<RadialGradientTexture
						width={128}
						height={128}
						innerRadius={0.2}
						outerRadius="auto"
						center.x={0.5}
						center.y={0.5}
						stops={[
							{ color: '#8a2be2', offset: 0 },
							{ color: '#ff1497', offset: 1 }
						]}
					/>
				</T.MeshBasicMaterial>
			</T.Mesh>
			<T.Mesh
				geometry={gltf.nodes.Cube023.geometry}
				material={gltf.nodes.Cube023.material}
				position={[-0.2, -4.7, 0.45]}
				scale={[0.25, 0.25, 0.05]}
			>
				<T.MeshBasicMaterial side={DoubleSide}>
					<RadialGradientTexture
						width={128}
						height={128}
						innerRadius={0.2}
						outerRadius="auto"
						center.x={0.5}
						center.y={0.5}
						stops={[
							{ color: '#00bfff', offset: 0 },
							{ color: '#8a2be2', offset: 1 }
						]}
					/>
				</T.MeshBasicMaterial>
			</T.Mesh>
			<T.Mesh
				geometry={gltf.nodes.Cube024.geometry}
				material={gltf.nodes.Cube024.material}
				position={[-0.2, -5.7, 0.45]}
				scale={[0.25, 0.25, 0.05]}
			>
				<T.MeshBasicMaterial>
					<RadialGradientTexture
						width={128}
						height={128}
						innerRadius={0.2}
						outerRadius="auto"
						center.x={0.5}
						center.y={0.5}
						stops={[
							{ color: '#ffd700', offset: 0 },
							{ color: '#ff1497', offset: 1 }
						]}
					/>
				</T.MeshBasicMaterial>
			</T.Mesh>
			<!-- Floating Payment Notifications -->
			<HTML scale={0.4} transform position={[3.5, -2.5, 0.3]} style="pointer-events: none;" occlude>
				<div class="floating-notification-tailwind">
					<div class="flex items-center gap-2">
						<span class="text-lg animate-bounce">⚡</span>
						<span class="text-xs font-semibold text-white animate-pulse">Payment Instant</span>
						<span class="text-sm font-bold text-yellow-400 drop-shadow-lg animate-pulse"
							>+ $0.05</span
						>
					</div>
				</div>
			</HTML>

			<HTML
				transform
				position={[-3.2, -5.5, 0.5]}
				style="pointer-events: none;"
				scale={0.4}
				occlude
			>
				<div class="floating-notification-tailwind">
					<div class="flex items-center gap-2">
						<span class="text-lg animate-bounce">💳</span>
						<span class="text-xs font-semibold text-white animate-pulse"
							>Transaction successful</span
						>
						<span class="text-sm font-bold text-yellow-400 drop-shadow-lg animate-pulse"
							>+ $0.02</span
						>
					</div>
				</div>
			</HTML>
		</T.Group>

		<T.Group position={[0, 4, 0]}>
			<T.Mesh
				geometry={gltf.nodes.Cylinder.geometry}
				material={gltf.materials['Material.002']}
				position={[-1.6, -1.59, 0.36]}
				rotation={[Math.PI / 2, 0, 0]}
				scale={0.1}
			>
				<MeshLineMaterial lineWidth={0.02} color="#ff1497" />
			</T.Mesh>
			<T.Mesh
				geometry={gltf.nodes.Cylinder001.geometry}
				material={gltf.materials['Material.003']}
				position={[-1.3, -1.59, 0.36]}
				rotation={[Math.PI / 2, 0, 0]}
				scale={0.1}
			>
				<MeshLineMaterial lineWidth={0.02} color="#ffd700" />
			</T.Mesh>
			<T.Mesh
				geometry={gltf.nodes.Cylinder002.geometry}
				material={gltf.materials['Material.004']}
				position={[-1, -1.59, 0.36]}
				rotation={[Math.PI / 2, 0, 0]}
				scale={0.1}
			>
				<MeshLineMaterial lineWidth={0.02} color="#00bfff" />
			</T.Mesh>
		</T.Group>

		<T.Mesh
			geometry={gltf.nodes.header.geometry}
			material={gltf.materials['Material.009']}
			position={[0, 2.4, 0.3]}
			scale={[1.8, 0.4, 0.05]}
		>
			<MeshLineMaterial lineWidth={0.02} color="#1e293b" />
		</T.Mesh>

		<T.Mesh
			name="phone"
			geometry={gltf.nodes.phone.geometry}
			material={gltf.nodes.phone.material}
			scale={[2, 3, 0.15]}
		>
			<Outlines color="#1403ff" thickness={0.03} />
			<MeshLineMaterial lineWidth={0.02} color="#c1b0d9" />
		</T.Mesh>

		<T.Mesh
			geometry={gltf.nodes.menu001.geometry}
			material={gltf.materials['Material.009']}
			position={[0, -2.55, 0.3]}
			scale={[1.8 * scaleMenu001.current, 0.25 * scaleMenu001.current, 0.05]}
		>
			<MeshLineMaterial lineWidth={0.02} color="#1e293b" />

			<T.Group position={[-0.71, -0.4, 3]} scale={[0.22, 0.2, 1]}>
				<T.Mesh
					geometry={gltf.nodes.Cube060.geometry}
					material={gltf.materials['Material.014']}
					scale={scaleCube060.current}
					onpointerenter={() => {
						scaleCube060.target = 1.1;
					}}
					onpointerleave={() => {
						scaleCube060.target = 1;
					}}
				>
					<MeshLineMaterial lineWidth={0.02} color="#ff0396" />
				</T.Mesh>
				<T.Mesh
					geometry={gltf.nodes.Cube060_1.geometry}
					material={gltf.materials['Material.015']}
					position={[0.2, 0, 0]}
					scale={scaleCube060_1.current}
					onpointerenter={() => {
						scaleCube060_1.target = 1.1;
					}}
					onpointerleave={() => {
						scaleCube060_1.target = 1;
					}}
				>
					<MeshLineMaterial lineWidth={0.02} color="#ffe603" />
				</T.Mesh>
			</T.Group>

			<T.Group position={[0.01, 0.43, 3]} rotation={[0, 0, Math.PI]} scale={[0.33, 0.2, 1]}>
				<T.Mesh
					position={[-0.2, 0, 0]}
					geometry={gltf.nodes.Cube061.geometry}
					material={gltf.materials['Material.021']}
					scale={scaleCube061.current}
					onpointerenter={() => {
						scaleCube061.target = 1.1;
					}}
					onpointerleave={() => {
						scaleCube061.target = 1;
					}}
				>
					<MeshLineMaterial lineWidth={0.02} color="#0bff03" />
				</T.Mesh>
				<T.Mesh
					geometry={gltf.nodes.Cube061_1.geometry}
					material={gltf.materials['Material.015']}
					scale={scaleCube061_1.current}
					onpointerenter={() => {
						scaleCube061_1.target = 1.1;
					}}
					onpointerleave={() => {
						scaleCube061_1.target = 1;
					}}
				>
					<MeshLineMaterial lineWidth={0.02} color="#ff9100" />
				</T.Mesh>
			</T.Group>

			<T.Mesh
				geometry={gltf.nodes.Cube039.geometry}
				material={gltf.materials['Material.028']}
				position={[0.7, -0.4, 3]}
				scale={[0.22 * scaleCube039.current, 0.2 * scaleCube039.current, 1]}
				onpointerenter={() => {
					scaleCube039.target = 1.1;
				}}
				onpointerleave={() => {
					scaleCube039.target = 1;
				}}
			>
				<MeshLineMaterial lineWidth={0.02} color="#03ffe1" />
			</T.Mesh>
		</T.Mesh>

		<T.Mesh
			geometry={gltf.nodes.aptos.geometry}
			material={gltf.nodes.aptos.material}
			position={[1.7, 2.6, 0.45]}
			rotation={[Math.PI / 2, 0, 0]}
      scale={1.2}
		>
			<Outlines color="#00bfff" thickness={0.02} />
			<!-- <MeshLineMaterial lineWidth={0.02} color="white" /> -->
			<FakeGlowMaterial glowColor="#ffd700" depthTest={true} />
		</T.Mesh>
	</T.Group>
{/await}

<style>
	/* Floating Notification Animations */
	@keyframes floatUp {
		0%,
		100% {
			transform: translateY(0px) scale(1);
			opacity: 0.8;
		}
		50% {
			transform: translateY(-10px) scale(1.05);
			opacity: 1;
		}
	}

	@keyframes glowPulse {
		0%,
		100% {
			box-shadow: 0 4px 20px rgba(0, 191, 255, 0.3);
		}
		50% {
			box-shadow: 0 8px 30px rgba(0, 191, 255, 0.6);
		}
	}

	@keyframes fadeInUp {
		from {
			opacity: 0;
			transform: translateY(20px);
		}
		to {
			opacity: 1;
			transform: translateY(0);
		}
	}

	.floating-notification-tailwind {
		background: linear-gradient(135deg, rgba(0, 191, 255, 0.15) 0%, rgba(138, 43, 226, 0.15) 100%);
		backdrop-filter: blur(8px);
		border: 1px solid rgba(0, 191, 255, 0.4);
		border-radius: 12px;
		padding: 12px 16px;
		box-shadow: 0 4px 20px rgba(0, 191, 255, 0.3);
		animation:
			floatUp 4s ease-in-out infinite,
			glowPulse 2s ease-in-out infinite;
		transform-style: preserve-3d;
	}

	.floating-notification-tailwind:hover {
		animation-duration: 2s, 1s;
		transform: scale(1.05);
	}
</style>
